from app.api.lookup_retrieve import router as lookup_router
from app.api.auth import router as auth_router
from app.api.users import router as users_router
from app.api.doc_spaces import router as doc_spaces_router
from app.api.documents import router as documents_router
from app.api.chat import router as chat_router
from app.api.conversations import router as conversations_router
from app.api.gaps import router as gaps_router
from app.api.notifications import router as notifications_router
from app.api.dashboard import router as dashboard_router
from app.api.faq import router as faq_router
